#!/usr/bin/env bash
# ══════════════════════════════════════════════════════════════════
#  NetSleuth — System-Wide Installer
#
#  Creates the global command "netsleuth" at /usr/local/bin/netsleuth
#  so you can run the tool from any directory.
#
#  Usage:
#    chmod +x install_sys.sh
#    sudo ./install_sys.sh
#
#  After installation:
#    netsleuth              →  Launch web dashboard
#    netsleuth update       →  Pull latest code + update deps
# ══════════════════════════════════════════════════════════════════

set -e

# ── Colors ────────────────────────────────────────────────────────
R='\033[0;91m'
G='\033[0;92m'
Y='\033[0;93m'
C='\033[0;96m'
B='\033[1m'
D='\033[2m'
RST='\033[0m'

ok()   { echo -e "  ${G}✔${RST}  $1"; }
err()  { echo -e "  ${R}✖${RST}  $1" >&2; }
info() { echo -e "  ${C}ℹ${RST}  $1"; }

die() { err "$1"; exit 1; }

# ── Must be root ──────────────────────────────────────────────────
if [ "$(id -u)" -ne 0 ]; then
    die "Este script necesita root. Ejecuta: ${B}sudo ./install_sys.sh${RST}"
fi

# ── Detect project directory (where this script lives) ────────────
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
INSTALL_DIR="$SCRIPT_DIR"

echo ""
echo -e "  ${C}${B}╔══════════════════════════════════════════════════╗${RST}"
echo -e "  ${C}${B}║   NetSleuth — Instalador de Comando Global      ║${RST}"
echo -e "  ${C}${B}╚══════════════════════════════════════════════════╝${RST}"
echo ""

info "Directorio del proyecto: ${B}${INSTALL_DIR}${RST}"

# ── Verify project files exist ────────────────────────────────────
[ -f "${INSTALL_DIR}/main.py" ]         || die "main.py no encontrado en ${INSTALL_DIR}"
[ -f "${INSTALL_DIR}/requirements.txt" ] || die "requirements.txt no encontrado"

# ── Verify virtual environment ────────────────────────────────────
VENV_PYTHON="${INSTALL_DIR}/env/bin/python"

if [ ! -f "$VENV_PYTHON" ]; then
    echo ""
    info "Entorno virtual no encontrado. Creando..."
    python3 -m venv "${INSTALL_DIR}/env" || die "No se pudo crear el venv."
    # shellcheck disable=SC1091
    source "${INSTALL_DIR}/env/bin/activate"
    pip install --upgrade pip > /dev/null 2>&1
    pip install -r "${INSTALL_DIR}/requirements.txt" || die "pip install falló."
    deactivate 2>/dev/null || true
    ok "Entorno virtual creado e instalado."
fi

ok "Python del venv: ${VENV_PYTHON}"

# ── Create the wrapper at /usr/local/bin/netsleuth ────────────────
TARGET="/usr/local/bin/netsleuth"

echo ""
info "Creando ${B}${TARGET}${RST}..."

cat > "$TARGET" << WRAPPER_EOF
#!/usr/bin/env bash
# ── NetSleuth Global Wrapper (auto-generated by install_sys.sh) ──
# Project: ${INSTALL_DIR}
# Generated: $(date '+%Y-%m-%d %H:%M:%S')

INSTALL_DIR="${INSTALL_DIR}"
VENV_PYTHON="\${INSTALL_DIR}/env/bin/python"

# ── Colors ──
R='\033[0;91m'; G='\033[0;92m'; Y='\033[0;93m'
C='\033[0;96m'; B='\033[1m'; D='\033[2m'; RST='\033[0m'

die()  { echo -e "  \${R}\${B}✖  \$1\${RST}" >&2; exit 1; }
ok()   { echo -e "  \${G}✔\${RST}  \$1"; }
info() { echo -e "  \${C}ℹ\${RST}  \$1"; }
warn() { echo -e "  \${Y}⚠\${RST}  \$1"; }

# ── Validate ──
[ -d "\$INSTALL_DIR" ] || die "Directorio no encontrado: \$INSTALL_DIR"
[ -f "\$VENV_PYTHON" ] || die "Venv no encontrado: \$VENV_PYTHON"

# ── Handle 'update' subcommand ──
if [ "\${1:-}" = "update" ]; then
    echo ""
    echo -e "  \${C}\${B}NetSleuth — Actualizando...\${RST}"
    echo ""

    cd "\$INSTALL_DIR" || die "No se pudo acceder a \$INSTALL_DIR"

    # Check connectivity
    if ! ping -c 1 -W 3 github.com > /dev/null 2>&1; then
        if ! ping -c 1 -W 3 1.1.1.1 > /dev/null 2>&1; then
            die "Sin conexión a internet."
        fi
    fi
    ok "Conexión verificada."

    # Pull
    BRANCH=\$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "main")
    BEFORE=\$(git rev-parse --short HEAD 2>/dev/null)
    git pull origin "\$BRANCH" 2>&1 || die "git pull falló."
    AFTER=\$(git rev-parse --short HEAD 2>/dev/null)

    if [ "\$BEFORE" = "\$AFTER" ]; then
        ok "Ya estás en la última versión (\$AFTER)."
    else
        ok "Actualizado: \$BEFORE → \$AFTER"
    fi

    # Update deps
    source "\${INSTALL_DIR}/env/bin/activate" 2>/dev/null
    pip install -r "\${INSTALL_DIR}/requirements.txt" --upgrade -q 2>&1
    ok "Dependencias actualizadas."
    deactivate 2>/dev/null || true

    echo ""
    echo -e "  \${G}\${B}✔  NetSleuth actualizado correctamente.\${RST}"
    echo ""
    exit 0
fi

# ── Auto-escalate to root ──
if [ "\$(id -u)" -ne 0 ]; then
    info "Requiere root — re-ejecutando con sudo..."
    exec sudo "\$0" "\$@"
fi

# ── Launch ──
exec "\$VENV_PYTHON" "\${INSTALL_DIR}/main.py" "\$@"
WRAPPER_EOF

# ── Make executable ───────────────────────────────────────────────
chmod +x "$TARGET"
ok "Wrapper creado en ${B}${TARGET}${RST}"

# ── Verify ────────────────────────────────────────────────────────
echo ""
if command -v netsleuth > /dev/null 2>&1; then
    echo -e "  ${G}${B}╔══════════════════════════════════════════════════╗${RST}"
    echo -e "  ${G}${B}║   ✔  Comando 'netsleuth' instalado globalmente  ║${RST}"
    echo -e "  ${G}${B}╚══════════════════════════════════════════════════╝${RST}"
    echo ""
    info "Ubicación: $(which netsleuth)"
    info "Proyecto:  ${INSTALL_DIR}"
    echo ""
    echo -e "  ${Y}Comandos disponibles:${RST}"
    echo -e "    ${B}netsleuth${RST}              Lanzar Web Dashboard"
    echo -e "    ${B}netsleuth update${RST}       Actualizar desde GitHub"
    echo ""
else
    err "/usr/local/bin no está en tu PATH."
    info "Añade esto a tu ~/.bashrc:"
    echo '    export PATH="/usr/local/bin:$PATH"'
fi
